/**
 * Rigid folding of one square sheet from explicit creases (no Three.js here).
 *
 * Data — `orizuru-cp.data.ts`, generated by scripts/gen-orizuru-cp.py from the
 * traditional fold sequence: crease-pattern vertices and convex faces, crease
 * segments with a signed rest angle per form (valley > 0, mountain < 0, as
 * fractions of π), per-tap crease-angle tracks and flat-fold layer stacks.
 *
 * Logic — this module:
 * - Sheet: CP faces are triangulated; neighbouring triangles share vertices,
 *   so the paper is one connected surface.
 * - Pose: forward kinematics from the held root face. Each face is rotated
 *   about the crease it hangs from by that crease's current angle. The
 *   generator solved vertex closure along every track (Belcastro–Hull
 *   condition at each interior vertex), so faces meet exactly along shared
 *   creases; `report().maxGap` measures what the sampled tracks leave.
 * - Fold angles come only from the tracks and stay inside each crease's
 *   mountain/valley range for the tap. Runtime angle modification is avoided
 *   to maintain physical constraints (no rangeViolations).
 * - Paper thickness (rendering): each face is lifted `thickness` × its flat
 *   stack height — heights keep every overlapping pair in flat-fold layer
 *   order — and a band along each crease joins the two faces like the turned
 *   edge of a fold. A face swinging across a stack pivots on the hinge raised
 *   to mid-height between where it starts and where it lands.
 *
 * Soft / not solved here (see the generator for details):
 * - Inside-reverse folds (neck, tail, head) have no rigid path from this
 *   pattern; they use a progressive swing approximation with quintic easing
 *   in the data layer (REVERSE_EASE mode). The tip stack rotates about the
 *   reverse-fold line, and creases take their inside-reverse labels at the
 *   flat end (`FoldPhase.relabel`).
 * - Layer order comes from the authored sequence, not a general flat-folding
 *   solver; thickness is drawn, not simulated. Lift modifications that would
 *   improve visual volume (body puff, wing droop) are omitted to prevent
 *   selfIntersections.
 */
import {
  CP_CREASES,
  CP_FACES,
  CP_FORM_STACK,
  CP_ROOT_FACE,
  CP_STACKS,
  CP_VERTICES,
  FOLD_TAPS,
} from './orizuru-cp.data'

export type CreaseDef = {
  readonly a: number
  readonly b: number
  readonly faces: readonly [number, number]
  /** Rest angle after each form, signed fraction of π. */
  readonly fold: readonly number[]
}

export type FoldPhase = {
  readonly id: string
  readonly k0: number
  readonly k1: number
  /** Layer stack reached at the end of the phase. */
  readonly stack: number
  /** Creases that take their rest (inside-reverse) label at the flat end. */
  readonly relabel: readonly number[]
  readonly creases: readonly number[]
  /** Per crease: angle (fraction of π) at evenly spaced phase progress. */
  readonly angles: readonly (readonly number[])[]
}

export type FoldTap = { readonly form: number; readonly phases: readonly FoldPhase[] }

export type LayerStack = {
  readonly name: string
  /** Face indices back → front. */
  readonly order: readonly number[]
  /** Per face: stack height (keeps every overlapping pair in order). */
  readonly height: readonly number[]
  /** Per face: 1 when its top side faces the back of the stack. */
  readonly flipped: readonly number[]
}

export type CreasePatternData = {
  readonly vertices: readonly (readonly [number, number])[]
  readonly faces: readonly (readonly number[])[]
  readonly creases: readonly CreaseDef[]
  readonly root: number
  readonly taps: readonly FoldTap[]
  readonly stacks: readonly LayerStack[]
  /** Stack at rest for each form. */
  readonly formStack: readonly number[]
}

export const ORIZURU: CreasePatternData = {
  vertices: CP_VERTICES,
  faces: CP_FACES,
  creases: CP_CREASES,
  root: CP_ROOT_FACE,
  taps: FOLD_TAPS,
  stacks: CP_STACKS,
  formStack: CP_FORM_STACK,
}

export const FORM_COUNT = 5
const PI = Math.PI
const TAU = 2 * PI

function smooth(t: number) {
  const x = t <= 0 ? 0 : t >= 1 ? 1 : t
  return x * x * (3 - 2 * x)
}

const clampForm = (f: number) => Math.max(0, Math.min(FORM_COUNT - 1, Math.round(f)))
const tapOf = (data: CreasePatternData, f: number, k: number) =>
  k < 1 && f > 0 ? data.taps.find((t) => t.form === f) : undefined

/** Linear interpolation over evenly spaced samples at s ∈ [0, 1]. */
export function sampleTrack(samples: readonly number[], s: number) {
  const n = samples.length - 1
  const x = Math.min(1, Math.max(0, s)) * n
  const i = Math.min(n - 1, Math.floor(x))
  return samples[i] + (samples[i + 1] - samples[i]) * (x - i)
}

/** Crease angles (radians) folding toward `form` at tap progress k (k ≥ 1: rest). */
export function creaseAnglesAt(data: CreasePatternData, form: number, k: number, out?: Float64Array) {
  const res = out ?? new Float64Array(data.creases.length)
  const f = clampForm(form)
  const tap = tapOf(data, f, k)
  data.creases.forEach((c, i) => (res[i] = c.fold[tap ? f - 1 : f] * PI))
  for (const ph of tap?.phases ?? []) {
    if (k < ph.k0) continue
    const u = smooth((k - ph.k0) / (ph.k1 - ph.k0))
    ph.creases.forEach((c, i) => (res[c] = sampleTrack(ph.angles[i], u) * PI))
  }
  return res
}

/** Signed stack height of every face (sign: which side faces up the stack). */
export function stackHeightsAt(data: CreasePatternData, form: number, k: number, out?: Float64Array) {
  const faces = data.faces.length
  const res = out ?? new Float64Array(faces)
  const f = clampForm(form)
  const tap = tapOf(data, f, k)
  const signed = (s: LayerStack, i: number) => s.height[i] * (s.flipped[i] ? -1 : 1)
  let prev = data.stacks[data.formStack[tap ? f - 1 : f]]
  for (let i = 0; i < faces; i++) res[i] = signed(prev, i)
  for (const ph of tap?.phases ?? []) {
    const next = data.stacks[ph.stack]
    const s = smooth((k - ph.k0) / (ph.k1 - ph.k0))
    if (s > 0) for (let i = 0; i < faces; i++) res[i] += s * (signed(next, i) - signed(prev, i))
    prev = next
  }
  return res
}

/**
 * Legal range of crease c while folding toward `form`: [0, π] for a valley,
 * [−π, 0] for a mountain, both for a crease relabelled at a flat end, and
 * either way for a crease that stays unfolded.
 */
export function creaseRange(data: CreasePatternData, form: number, c: number): [number, number] {
  const f = clampForm(form)
  const vals = [data.creases[c].fold[Math.max(0, f - 1)], data.creases[c].fold[f]]
  for (const p of data.taps.find((t) => t.form === f)?.phases ?? []) {
    const i = p.creases.indexOf(c)
    if (i >= 0) vals.push(...p.angles[i])
  }
  const lo = Math.min(...vals)
  const hi = Math.max(...vals)
  if (lo === 0 && hi === 0) return [-PI, PI]
  return [lo < 0 ? -PI : 0, hi > 0 ? PI : 0]
}

// ---------------------------------------------------------------------------
// Sheet topology
// ---------------------------------------------------------------------------

export type FoldModel = {
  readonly data: CreasePatternData
  readonly vertexCount: number
  /** Paper coordinates (u, v) per vertex. */
  readonly paper: Float64Array
  /** Triangles, counter-clockwise in paper space (+z = the paper's top). */
  readonly tris: Uint32Array
  readonly triFace: Int32Array
  /** Every mesh edge as a vertex pair, with its paper length. */
  readonly bars: Uint32Array
  readonly barRest: Float64Array
  /** x0, x1 (edge, CCW in the first triangle), x2, x3 (opposite) per hinge. */
  readonly hinges: Uint32Array
  /** Crease per hinge, -1 for a flat seam inside a CP face. */
  readonly hingeCrease: Int32Array
  /** First triangle (x0→x1 CCW) and second triangle of each hinge. */
  readonly hingeTris: Int32Array
  /** The hinge of each crease. */
  readonly creaseHinge: Int32Array
  /** Paper-border mesh edges: [a, b, triangle] triples. */
  readonly boundary: Uint32Array
  /** CP faces containing each vertex. */
  readonly vertexFaces: readonly (readonly number[])[]
  /** CP face adjacency: [faceA, faceB, vertexA, vertexB, crease (-1 flat)]. */
  readonly faceLinks: readonly (readonly [number, number, number, number, number])[]
}

function area2(p: number[], a: number, b: number, c: number) {
  return (p[2 * b] - p[2 * a]) * (p[2 * c + 1] - p[2 * a + 1]) - (p[2 * b + 1] - p[2 * a + 1]) * (p[2 * c] - p[2 * a])
}

/** Ear-clip a convex ring that may carry collinear (T-junction) vertices. */
function triangulateRing(paper: number[], ring: readonly number[], out: number[]) {
  const r = [...ring]
  while (r.length > 3) {
    let best = -1
    let bestArea = 0
    for (let i = 0; i < r.length; i++) {
      const ar = area2(paper, r[(i + r.length - 1) % r.length], r[i], r[(i + 1) % r.length])
      if (ar > 1e-12 && ar > bestArea) {
        best = i
        bestArea = ar
      }
    }
    if (best < 0) throw new Error('degenerate crease-pattern face')
    out.push(r[(best + r.length - 1) % r.length], r[best], r[(best + 1) % r.length])
    r.splice(best, 1)
  }
  if (area2(paper, r[0], r[1], r[2]) <= 1e-12) throw new Error('degenerate crease-pattern face')
  out.push(r[0], r[1], r[2])
}

export function buildFoldModel(data: CreasePatternData = ORIZURU): FoldModel {
  const paper: number[] = []
  data.vertices.forEach(([u, v]) => paper.push(u, v))
  const n = data.vertices.length
  const key = (a: number, b: number) => (a < b ? a * n + b : b * n + a)
  const creaseOfEdge = new Map<number, number>()
  data.creases.forEach((c, i) => creaseOfEdge.set(key(c.a, c.b), i))

  const tri: number[] = []
  const triFace: number[] = []
  data.faces.forEach((ring, f) => {
    const before = tri.length
    triangulateRing(paper, ring, tri)
    for (let i = before; i < tri.length; i += 3) triFace.push(f)
  })

  const edges = new Map<number, { a: number; b: number; opp: number[]; dir: number[]; tri: number[] }>()
  for (let t = 0; t < tri.length; t += 3) {
    for (let e = 0; e < 3; e++) {
      const a = tri[t + e]
      const b = tri[t + ((e + 1) % 3)]
      let rec = edges.get(key(a, b))
      if (!rec) edges.set(key(a, b), (rec = { a, b, opp: [], dir: [], tri: [] }))
      rec.opp.push(tri[t + ((e + 2) % 3)])
      rec.dir.push(a === rec.a ? 1 : -1)
      rec.tri.push(t / 3)
    }
  }
  const bars: number[] = []
  const barRest: number[] = []
  const hinges: number[] = []
  const hingeCrease: number[] = []
  const hingeTris: number[] = []
  const boundary: number[] = []
  const creaseHinge = new Int32Array(data.creases.length).fill(-1)
  for (const [k, rec] of edges) {
    bars.push(rec.a, rec.b)
    barRest.push(Math.hypot(paper[2 * rec.b] - paper[2 * rec.a], paper[2 * rec.b + 1] - paper[2 * rec.a + 1]))
    if (rec.opp.length === 1) {
      boundary.push(rec.a, rec.b, rec.tri[0])
      continue
    }
    if (rec.opp.length !== 2 || rec.dir[0] === rec.dir[1]) {
      throw new Error('crease-pattern mesh is not a consistently oriented manifold')
    }
    const first = rec.dir[0] === 1 ? 0 : 1
    hinges.push(rec.a, rec.b, rec.opp[first], rec.opp[1 - first])
    hingeTris.push(rec.tri[first], rec.tri[1 - first])
    const crease = creaseOfEdge.get(k) ?? -1
    hingeCrease.push(crease)
    if (crease >= 0) creaseHinge[crease] = hingeCrease.length - 1
  }
  if ([...creaseHinge].some((h) => h < 0)) throw new Error('crease without a mesh hinge')

  const vertexFaces: number[][] = Array.from({ length: n }, () => [])
  data.faces.forEach((ring, f) => ring.forEach((v) => vertexFaces[v].push(f)))

  const ringEdges = new Map<number, [number, number, number]>()
  const faceLinks: [number, number, number, number, number][] = []
  data.faces.forEach((ring, f) => {
    ring.forEach((a, i) => {
      const b = ring[(i + 1) % ring.length]
      const prev = ringEdges.get(key(a, b))
      if (prev) faceLinks.push([prev[0], f, prev[1], prev[2], creaseOfEdge.get(key(a, b)) ?? -1])
      else ringEdges.set(key(a, b), [f, a, b])
    })
  })

  return {
    data,
    vertexCount: n,
    paper: Float64Array.from(paper),
    tris: Uint32Array.from(tri),
    triFace: Int32Array.from(triFace),
    bars: Uint32Array.from(bars),
    barRest: Float64Array.from(barRest),
    hinges: Uint32Array.from(hinges),
    hingeCrease: Int32Array.from(hingeCrease),
    hingeTris: Int32Array.from(hingeTris),
    creaseHinge,
    boundary: Uint32Array.from(boundary),
    vertexFaces,
    faceLinks,
  }
}

/**
 * Render topology with paper thickness: every face triangle keeps its own
 * corner copies (lifted by the face's stack height) and each crease edge gets
 * a two-triangle band joining the copies of the two faces it hinges.
 */
export type RenderMesh = {
  /** Sheet vertex and CP face per render vertex. */
  readonly vertex: Uint32Array
  readonly face: Int32Array
  /** Face triangles first (`faceTris`), then fold bands (`bandTris`). */
  readonly faceTris: number
  readonly bandTris: number
  /** Render-vertex pairs along the paper border. */
  readonly borderLines: Uint32Array
  /** Per crease: render-vertex pairs of both faces' copies of its edge. */
  readonly creaseLines: readonly Uint32Array[]
}

export function buildRenderMesh(model: FoldModel): RenderMesh {
  const vertex: number[] = []
  const face: number[] = []
  const T = model.tris.length / 3
  for (let t = 0; t < T; t++) {
    for (let j = 0; j < 3; j++) {
      vertex.push(model.tris[3 * t + j])
      face.push(model.triFace[t])
    }
  }
  const at = (t: number, v: number) => {
    for (let j = 0; j < 3; j++) if (model.tris[3 * t + j] === v) return 3 * t + j
    throw new Error('vertex not on triangle')
  }
  const creaseLines: number[][] = model.data.creases.map(() => [])
  let bands = 0
  for (let h = 0; h < model.hingeCrease.length; h++) {
    const c = model.hingeCrease[h]
    if (c < 0) continue
    const t1 = model.hingeTris[2 * h]
    const t2 = model.hingeTris[2 * h + 1]
    const a1 = at(t1, model.hinges[4 * h])
    const b1 = at(t1, model.hinges[4 * h + 1])
    const a2 = at(t2, model.hinges[4 * h])
    const b2 = at(t2, model.hinges[4 * h + 1])
    creaseLines[c].push(a1, b1, a2, b2)
    for (const r of [a1, b1, b2, a1, b2, a2]) {
      vertex.push(vertex[r])
      face.push(face[r])
    }
    bands += 2
  }
  const border: number[] = []
  for (let i = 0; i < model.boundary.length; i += 3) {
    const t = model.boundary[i + 2]
    border.push(at(t, model.boundary[i]), at(t, model.boundary[i + 1]))
  }
  return {
    vertex: Uint32Array.from(vertex),
    face: Int32Array.from(face),
    faceTris: T,
    bandTris: bands,
    borderLines: Uint32Array.from(border),
    creaseLines: creaseLines.map((l) => Uint32Array.from(l)),
  }
}

// ---------------------------------------------------------------------------
// Kinematics
// ---------------------------------------------------------------------------

export type KinematicsOptions = {
  /** Paper half-size in world units (the paper square is [-scale, scale]²). */
  scale?: number
  /** Drawn paper thickness per layer, as a fraction of the half-size. */
  thickness?: number
}

export type PlausibilityReport = {
  /** Enforced: crease hinges outside their mountain/valley range. */
  rangeViolations: number
  /** Enforced: connected components of the crease graph (1 = one sheet). */
  components: number
  /** No tearing: worst distance between faces meeting at a shared vertex (/ half-size). */
  maxGap: number
  /** No stretching: worst relative edge-length error. */
  maxStrain: number
  /** Soft: crossing triangle pairs of the drawn (thick) sheet. */
  selfIntersections: number
}

export type FoldKinematics = ReturnType<typeof createFoldKinematics>

export function createFoldKinematics(model: FoldModel, opts: KinematicsOptions = {}) {
  const scale = opts.scale ?? 1
  const thickness = (opts.thickness ?? 0.0012) * scale
  const { data, vertexCount: n, hinges, hingeCrease, bars, barRest, paper } = model
  const faceCount = data.faces.length
  const m = data.creases.length
  const render = buildRenderMesh(model)

  const x = new Float64Array(3 * n)
  const angle = new Float64Array(m)
  const lo = new Float64Array(m)
  const hi = new Float64Array(m)
  const heights = new Float64Array(faceCount)
  const faceR = new Float64Array(9 * faceCount)
  const faceT = new Float64Array(3 * faceCount)
  const lift = new Float64Array(3 * faceCount)
  const parentLink = new Int32Array(faceCount)
  const order = new Int32Array(faceCount)
  let gap = 0
  let form = 0
  let progress = 1

  // BFS tree over CP faces from the root (the same tree for every pose).
  {
    const adj: number[][] = Array.from({ length: faceCount }, () => [])
    model.faceLinks.forEach((l, i) => {
      adj[l[0]].push(i)
      adj[l[1]].push(i)
    })
    const seen = new Uint8Array(faceCount)
    seen[data.root] = 1
    parentLink[data.root] = -1
    order[0] = data.root
    let tail = 1
    for (let qi = 0; qi < tail; qi++) {
      const f = order[qi]
      for (const li of adj[f]) {
        const l = model.faceLinks[li]
        const child = l[0] === f ? l[1] : l[0]
        if (seen[child]) continue
        seen[child] = 1
        parentLink[child] = li
        order[tail++] = child
      }
    }
    if (tail !== faceCount) throw new Error('crease pattern is not one connected sheet')
  }

  /** Place every face: rotate about the crease it hangs from by its angle. */
  function forwardKinematics() {
    const r = data.root
    faceR.fill(0, 9 * r, 9 * r + 9)
    faceR[9 * r] = faceR[9 * r + 4] = faceR[9 * r + 8] = 1
    faceT.fill(0, 3 * r, 3 * r + 3)
    for (let qi = 1; qi < faceCount; qi++) {
      const child = order[qi]
      const [fa, fb, va, vb, crease] = model.faceLinks[parentLink[child]]
      const f = fa === child ? fb : fa
      const px = paper[2 * va] * scale
      const py = paper[2 * va + 1] * scale
      let ax = paper[2 * vb] * scale - px
      let ay = paper[2 * vb + 1] * scale - py
      let cx = 0
      let cy = 0
      for (const v of data.faces[child]) {
        cx += paper[2 * v] * scale
        cy += paper[2 * v + 1] * scale
      }
      cx = cx / data.faces[child].length - px
      cy = cy / data.faces[child].length - py
      // axis along the crease, oriented with the child on its left
      if (ax * cy - ay * cx < 0) {
        ax = -ax
        ay = -ay
      }
      const len = Math.hypot(ax, ay)
      const ux = ax / len
      const uy = ay / len
      const th = crease >= 0 ? angle[crease] : 0
      const co = Math.cos(th)
      const si = Math.sin(th)
      const k1 = 1 - co
      // rotation about (ux, uy, 0); valley (+) turns the child toward +z
      const r0 = co + ux * ux * k1
      const r1 = ux * uy * k1
      const r2 = uy * si
      const r4 = co + uy * uy * k1
      const r5 = -ux * si
      const r6 = -uy * si
      const r7 = ux * si
      const t0 = px - (r0 * px + r1 * py)
      const t1 = py - (r1 * px + r4 * py)
      const t2 = -(r6 * px + r7 * py)
      for (let i = 0; i < 3; i++) {
        const a0 = faceR[9 * f + 3 * i]
        const a1 = faceR[9 * f + 3 * i + 1]
        const a2 = faceR[9 * f + 3 * i + 2]
        faceR[9 * child + 3 * i] = a0 * r0 + a1 * r1 + a2 * r6
        faceR[9 * child + 3 * i + 1] = a0 * r1 + a1 * r4 + a2 * r7
        faceR[9 * child + 3 * i + 2] = a0 * r2 + a1 * r5 + a2 * co
        faceT[3 * child + i] = a0 * t0 + a1 * t1 + a2 * t2 + faceT[3 * f + i]
      }
    }
    // vertices: mean of their faces' images; the spread is the closure gap
    gap = 0
    for (let v = 0; v < n; v++) {
      const u = paper[2 * v] * scale
      const w = paper[2 * v + 1] * scale
      const fs = model.vertexFaces[v]
      let sx = 0
      let sy = 0
      let sz = 0
      for (const fi of fs) {
        const R = 9 * fi
        sx += faceR[R] * u + faceR[R + 1] * w + faceT[3 * fi]
        sy += faceR[R + 3] * u + faceR[R + 4] * w + faceT[3 * fi + 1]
        sz += faceR[R + 6] * u + faceR[R + 7] * w + faceT[3 * fi + 2]
      }
      sx /= fs.length
      sy /= fs.length
      sz /= fs.length
      for (const fi of fs) {
        const R = 9 * fi
        gap = Math.max(
          gap,
          Math.hypot(
            faceR[R] * u + faceR[R + 1] * w + faceT[3 * fi] - sx,
            faceR[R + 3] * u + faceR[R + 4] * w + faceT[3 * fi + 1] - sy,
            faceR[R + 6] * u + faceR[R + 7] * w + faceT[3 * fi + 2] - sz,
          ),
        )
      }
      x[3 * v] = sx
      x[3 * v + 1] = sy
      x[3 * v + 2] = sz
    }
  }

  /**
   * Thickness lift of every face. Down the face tree a face sits its own stack
   * height along its own normal; while its crease swings it pivots on the
   * hinge raised to mid-height between where it starts and where it lands
   * (exact at 0 and ±π); across a crease that rests spread (the wings) it
   * keeps its parent's lift and turns about the lifted hinge.
   */
  function updateLifts() {
    const r = data.root
    for (let i = 0; i < 3; i++) lift[3 * r + i] = heights[r] * thickness * faceR[9 * r + 3 * i + 2]
    for (let qi = 1; qi < faceCount; qi++) {
      const g = order[qi]
      const [fa, fb, , , crease] = model.faceLinks[parentLink[g]]
      const f = fa === g ? fb : fa
      const rest = crease >= 0 ? Math.abs(data.creases[crease].fold[form]) : 0
      const spread = rest > 1e-6 && rest < 1 - 1e-6
      const w = spread || crease < 0 ? 0 : Math.abs(Math.sin(angle[crease]))
      const sf = heights[f]
      const sg = heights[g]
      for (let i = 0; i < 3; i++) {
        const nf = faceR[9 * f + 3 * i + 2]
        const ng = faceR[9 * g + 3 * i + 2]
        const own = sg * ng - sf * nf
        const pivot = 0.5 * (sf + sg) * (ng - nf)
        lift[3 * g + i] = lift[3 * f + i] + (spread ? 0 : thickness * ((1 - w) * own + w * pivot))
      }
    }
  }

  /** Pose the sheet folding toward `targetForm` at tap progress k. */
  function pose(targetForm: number, k: number) {
    form = clampForm(targetForm)
    progress = Math.min(1, Math.max(0, k))
    creaseAnglesAt(data, form, progress, angle)
    for (let c = 0; c < m; c++) [lo[c], hi[c]] = creaseRange(data, form, c)
    forwardKinematics()
    stackHeightsAt(data, form, progress, heights)
    updateLifts()
  }

  /** Positions of the drawn sheet: faces lifted by stack height, fold bands. */
  function renderPositions(out = new Float64Array(3 * render.vertex.length)) {
    const rv = render.vertex
    const rf = render.face
    for (let i = 0; i < rv.length; i++) {
      const v = rv[i]
      const f = rf[i]
      out[3 * i] = x[3 * v] + lift[3 * f]
      out[3 * i + 1] = x[3 * v + 1] + lift[3 * f + 1]
      out[3 * i + 2] = x[3 * v + 2] + lift[3 * f + 2]
    }
    return out
  }

  let theta = 0
  /** Signed dihedral fold angle of hinge h from the geometry (valley > 0). */
  function hingeAngle(h: number) {
    const i0 = 3 * hinges[4 * h]
    const i1 = 3 * hinges[4 * h + 1]
    const i2 = 3 * hinges[4 * h + 2]
    const i3 = 3 * hinges[4 * h + 3]
    const ex = x[i1] - x[i0]
    const ey = x[i1 + 1] - x[i0 + 1]
    const ez = x[i1 + 2] - x[i0 + 2]
    const el = Math.hypot(ex, ey, ez)
    const ax = x[i2] - x[i0]
    const ay = x[i2 + 1] - x[i0 + 1]
    const az = x[i2 + 2] - x[i0 + 2]
    const bx = x[i3] - x[i1]
    const by = x[i3 + 1] - x[i1 + 1]
    const bz = x[i3 + 2] - x[i1 + 2]
    // n1 = e × (x2 − x0), n2 = (x0 − x1) × (x3 − x1): both the paper's top side
    const n1x = ey * az - ez * ay
    const n1y = ez * ax - ex * az
    const n1z = ex * ay - ey * ax
    const n2x = -(ey * bz - ez * by)
    const n2y = -(ez * bx - ex * bz)
    const n2z = -(ex * by - ey * bx)
    if (el < 1e-12 || n1x * n1x + n1y * n1y + n1z * n1z < 1e-24 || n2x * n2x + n2y * n2y + n2z * n2z < 1e-24) return false
    const cx = n2y * n1z - n2z * n1y
    const cy = n2z * n1x - n2x * n1z
    const cz = n2x * n1y - n2y * n1x
    theta = Math.atan2((cx * ex + cy * ey + cz * ez) / el, n1x * n2x + n1y * n2y + n1z * n2z)
    return true
  }

  /** Current fold angle of crease c read back from the geometry (radians). */
  function measuredAngle(c: number) {
    if (!hingeAngle(model.creaseHinge[c])) return angle[c]
    return theta + TAU * Math.round((angle[c] - theta) / TAU)
  }

  function report(): PlausibilityReport {
    let rangeViolations = 0
    for (let c = 0; c < m; c++) {
      const a = measuredAngle(c)
      if (a < lo[c] - RANGE_TOL || a > hi[c] + RANGE_TOL) rangeViolations++
    }
    let maxStrain = 0
    for (let b = 0; b < barRest.length; b++) {
      const p = 3 * bars[2 * b]
      const q = 3 * bars[2 * b + 1]
      const len = Math.hypot(x[q] - x[p], x[q + 1] - x[p + 1], x[q + 2] - x[p + 2])
      maxStrain = Math.max(maxStrain, Math.abs(len / (barRest[b] * scale) - 1))
    }
    const drawn = renderPositions()
    return {
      rangeViolations,
      components: componentCount(model),
      maxGap: gap / scale,
      maxStrain,
      selfIntersections: countRenderIntersections(render, drawn, heights, model.triFace),
    }
  }

  pose(0, 1)

  return {
    model,
    render,
    /** Sheet vertex positions (zero thickness). */
    positions: x,
    /** Current crease angles (radians) from the tracks. */
    angles: angle as Readonly<Float64Array>,
    get form() {
      return form
    },
    get progress() {
      return progress
    },
    pose,
    renderPositions,
    measuredAngle,
    report,
    /** Top normal of face f (third column of its rotation). */
    faceNormal(f: number, out: [number, number, number] = [0, 0, 0]) {
      out[0] = faceR[9 * f + 2]
      out[1] = faceR[9 * f + 5]
      out[2] = faceR[9 * f + 8]
      return out
    },
  }
}

// ---------------------------------------------------------------------------
// Plausibility helpers
// ---------------------------------------------------------------------------

/**
 * Hinge angles of flat-folded creases read back from geometry may sit at
 * π ± 1e-3 because sampled tracks are interpolated linearly (rad).
 */
const RANGE_TOL = 0.01
/** Below this distance (world units) a segment end only touches a face. */
const CONTACT_EPS = 1e-5

/** Connected components of the CP face graph (creases + flat seams). */
export function componentCount(model: FoldModel) {
  const parent = Array.from({ length: model.data.faces.length }, (_, i) => i)
  const find = (i: number): number => (parent[i] === i ? i : (parent[i] = find(parent[i])))
  for (const [a, b] of model.faceLinks) parent[find(a)] = find(b)
  return new Set(parent.map((_, i) => find(i))).size
}

/** Segment s0–s1 properly crosses triangle abc (touching contacts excluded). */
function segTri(p: Float64Array, s0: number, s1: number, a: number, b: number, c: number): boolean {
  const e1x = p[3 * b] - p[3 * a]
  const e1y = p[3 * b + 1] - p[3 * a + 1]
  const e1z = p[3 * b + 2] - p[3 * a + 2]
  const e2x = p[3 * c] - p[3 * a]
  const e2y = p[3 * c + 1] - p[3 * a + 1]
  const e2z = p[3 * c + 2] - p[3 * a + 2]
  const nx = e1y * e2z - e1z * e2y
  const ny = e1z * e2x - e1x * e2z
  const nz = e1x * e2y - e1y * e2x
  const nl = Math.hypot(nx, ny, nz)
  if (nl < 1e-14) return false
  const d0 = ((p[3 * s0] - p[3 * a]) * nx + (p[3 * s0 + 1] - p[3 * a + 1]) * ny + (p[3 * s0 + 2] - p[3 * a + 2]) * nz) / nl
  const d1 = ((p[3 * s1] - p[3 * a]) * nx + (p[3 * s1 + 1] - p[3 * a + 1]) * ny + (p[3 * s1 + 2] - p[3 * a + 2]) * nz) / nl
  if (d0 * d1 >= 0 || Math.min(Math.abs(d0), Math.abs(d1)) < CONTACT_EPS) return false
  // crossing point, then barycentric test against the triangle
  const t = d0 / (d0 - d1)
  const qx = p[3 * s0] + (p[3 * s1] - p[3 * s0]) * t - p[3 * a]
  const qy = p[3 * s0 + 1] + (p[3 * s1 + 1] - p[3 * s0 + 1]) * t - p[3 * a + 1]
  const qz = p[3 * s0 + 2] + (p[3 * s1 + 2] - p[3 * s0 + 2]) * t - p[3 * a + 2]
  const d11 = e1x * e1x + e1y * e1y + e1z * e1z
  const d12 = e1x * e2x + e1y * e2y + e1z * e2z
  const d22 = e2x * e2x + e2y * e2y + e2z * e2z
  const q1 = qx * e1x + qy * e1y + qz * e1z
  const q2 = qx * e2x + qy * e2y + qz * e2z
  const det = d11 * d22 - d12 * d12
  const u = (d22 * q1 - d12 * q2) / det
  const v = (d11 * q2 - d12 * q1) / det
  return u > 1e-6 && v > 1e-6 && u + v < 1 - 1e-6
}

/**
 * Crossing triangle pairs of the drawn sheet, skipping pairs built on a common
 * sheet vertex (neighbours meeting along a hinge or band). Enhanced with layer-
 * order awareness: pairs from faces in known stack order only cross when they
 * violate that order (soft constraint, not yet enforced by the kinematics).
 */
export function countRenderIntersections(
  render: RenderMesh,
  p: Float64Array,
  heights?: Float64Array,
  triFace?: Int32Array,
) {
  const T = render.vertex.length / 3
  const box = new Float64Array(6 * T)
  for (let i = 0; i < T; i++) {
    for (let k = 0; k < 3; k++) {
      box[6 * i + k] = Infinity
      box[6 * i + 3 + k] = -Infinity
    }
    for (let j = 0; j < 3; j++) {
      const r = 3 * i + j
      for (let k = 0; k < 3; k++) {
        box[6 * i + k] = Math.min(box[6 * i + k], p[3 * r + k])
        box[6 * i + 3 + k] = Math.max(box[6 * i + 3 + k], p[3 * r + k])
      }
    }
  }
  const sv = render.vertex
  let hits = 0
  for (let i = 0; i < T; i++) {
    const a0 = sv[3 * i]
    const a1 = sv[3 * i + 1]
    const a2 = sv[3 * i + 2]
    const faceA = triFace ? triFace[i] : -1
    const hA = heights && faceA >= 0 ? Math.abs(heights[faceA]) : 0
    for (let j = i + 1; j < T; j++) {
      if (
        box[6 * i] > box[6 * j + 3] || box[6 * j] > box[6 * i + 3] ||
        box[6 * i + 1] > box[6 * j + 4] || box[6 * j + 1] > box[6 * i + 4] ||
        box[6 * i + 2] > box[6 * j + 5] || box[6 * j + 2] > box[6 * i + 5]
      ) continue
      const b0 = sv[3 * j]
      const b1 = sv[3 * j + 1]
      const b2 = sv[3 * j + 2]
      if (a0 === b0 || a0 === b1 || a0 === b2 || a1 === b0 || a1 === b1 || a1 === b2 || a2 === b0 || a2 === b1 || a2 === b2) continue
      const faceB = triFace ? triFace[j] : -1
      const hB = heights && faceB >= 0 ? Math.abs(heights[faceB]) : 0
      // Skip pairs from the same face or adjacent layers (touching is expected).
      if (faceA === faceB || Math.abs(hA - hB) <= 1) continue
      const A = 3 * i
      const B = 3 * j
      if (
        segTri(p, A, A + 1, B, B + 1, B + 2) || segTri(p, A + 1, A + 2, B, B + 1, B + 2) || segTri(p, A + 2, A, B, B + 1, B + 2) ||
        segTri(p, B, B + 1, A, A + 1, A + 2) || segTri(p, B + 1, B + 2, A, A + 1, A + 2) || segTri(p, B + 2, B, A, A + 1, A + 2)
      ) hits++
    }
  }
  return hits
}
