// Generated by prepare-app-assets.mjs from content/woodfish/bundled.json.
import { parsePack } from "./index";
export const bundledWoodfish = parsePack({
  "schemaVersion": 1,
  "sceneId": "woodfish",
  "engine": "woodfish@1",
  "renderStyle": "original",
  "revision": "bundled-woodfish-1",
  "model": {
    "path": "woodfish/bundled-v1/woodfish.glb",
    "bytes": 1763136,
    "sha256": "2a3ba9bf987ad3ec1d78519f48e65556f1c56fd40fcb7a236e922dabc7521185"
  },
  "bindings": {
    "body": "WoodfishBody",
    "mallet": "Mallet"
  },
  "parameters": {
    "headRadius": 0.255,
    "gripOffset": [
      0.65,
      -0.9,
      0.1
    ],
    "exposure": 1.1,
    "keyIntensity": 3.2,
    "fillIntensity": 0.65,
    "rimIntensity": 0.9,
    "liftMs": 170,
    "strikeMs": 95,
    "reboundMs": 95,
    "settleMs": 140
  },
  "copy": {
    "instruction": "悬浮或按住拖动木槌，轻点敲一下。"
  }
});
